idle:
  file: 'Resources/Music/States_of_player/idle.ogg'
  volume: 1.0

walking:
  file: 'Resources/Music/States_of_player/walking.ogg'
  volume: 0.5

running:
  file: 'Resources/Music/States_of_player/running.ogg'
  volume: 0.5

sitting:
  file: 'Resources/Music/States_of_player/sitting.ogg'
  volume: 0.3

squatting:
  file: 'Resources/Music/States_of_player/squatting.ogg'
  volume: 0.3

lying:
  file: 'Resources/Music/States_of_player/lying.ogg'
  volume: 0.3

crawling:
  file: 'Resources/Music/States_of_player/crawling.ogg'
  volume: 0.3

soaring:
  file: 'Resources/Music/States_of_player/soaring.ogg'
  volume: 0.3

jumping:
  file: 'Resources/Music/States_of_player/jumping.ogg'
  volume: 0.3

flying:
  file: 'Resources/Music/States_of_player/flying.ogg'
  volume: 0.3

landing:
  file: 'Resources/Music/States_of_player/landing.ogg'
  volume: 0.3

dying:
  file: 'Resources/Music/States_of_player/dying.ogg'
  volume: 1.0

win:
  file: 'Resources/Music/States_of_player/win.ogg'
  volume: 1.0


throw:
  file: 'Resources/Music/States_of_player/throw.ogg'
  volume: 0.1

hand_hit:
  file: 'Resources/Music/States_of_player/udar.ogg'
  volume: 0.5
