name: 'Default'

init:
  width: &width 0.96
  height: &height 1.8
  mass: 75
  animations: 'Resources/Animations/DanyaPers.yaml'
  sounds: 'Resources/Music/States_of_player/configs/danilio.yaml'

properties:
  description: null
  max_health: 100
  dodge: 0.1
  resistance: 0.1
  walk_speed: 1.5  # Скорость ходьбы сущности
  run_speed: 4  # Скорость бега сущности
  jump_speed: 8 # Скорость прыжка

hits:

  arming:
    hit_1:
      damage: 10

      impulse: 200
      impulse_angle: 1

      reload_time: 0.2
      box:
        x: 0.8
        y: 0.7
        w: 0.5
        h: 0.8
      animation: 'udar_1'
      animation_hatting_phase: 0.3
      sound: 'hand_hit'

    hit_2:
      damage: 10

      impulse: 100
      impulse_angle: 1

      reload_time: 0.2
      box:
        x: 0.8
        y: 0.7
        w: 0.5
        h: 0.8
      animation: 'udar_2'
      animation_hatting_phase: 0.3
      sound: 'hand_hit'

    hit_3:
      damage: 10

      impulse: 100
      impulse_angle: 1

      reload_time: 0.2
      box:
        x: 0.8
        y: 0.7
        w: 0.5
        h: 0.8
      animation: 'udar_3'
      animation_hatting_phase: 0.3
      sound: 'hand_hit'

  throwing:
    throw_1:
      damage: 20
      if_damaged: 'none'
      if_damaged_many: 'lose_damage'

      reload_time: 0.4

      item: 'TennisBall'

      position:
        - 1
        - 1

      throw_speed: 10
      throw_angle: 0.5235

      start_angle: 0
      angular_speed: 10

      animation: 'throw_1'
      animation_hatting_phase: 0.5
      sound: 'throw'

rects:
  idle_rect:
    - *width
    - *height
  walking_rect:
    - *width
    - *height
  running_rect:
    - *width
    - 1.72

  sitting_rect:
    - *width
    - 0.9
  squatting_rect:
    - *width
    - 0.9

  lying_rect:
    - *width
    - *height
  crawling_rect:
    - *width
    - *height

  soaring_rect:
    - *width
    - *height
  jumping_rect:
    - *width
    - *height
  flying_rect:
    - *width
    - *height
  landing_rect:
    - *width
    - *height


  dying_rect:
    - *height
    - 0.6

  win_rect:
    - *width
    - *height