name: 'MainCharacter'
description: null
init:
  width: 0.96
  height: 1.8
  mass: 75
  animations: 'Resources/Animations/maincharacter.yaml'
  sounds: 'Resources/Music/States_of_player/configs/maincharacter.yaml'